### ISSUE TITLE
Data Wrangling and Data frame used for plotting names

### ISSUE THREAD

**Issue by ghost** [Weifanwu66/Weifan-MADA-portfolio#3]
Hi Weifan, you did a really great job with this exercise. I found two things I would like to address, let me know what you think.

1.) For the Data Wrangling Section of your code

For this section, I see that you create three different objects "edu_div", "edu_div1", and "edu_div2" in your data wrangling code. I think this really helps the viewer follow along and understand why and how you are wrangling the data. In addition, I really enjoyed your comments which made it even easier to follow your code. 

My suggestion for the data wrangling section is to use the pipe operator (%>%) if you want to avoid making three different objects. I have provided an example below for your code:

edu_div=rawData %>%
        select(c(2,5:7)) %>%
        gather(key="education_level",value="divorce",2:4) %>%
        mutate(education_level=str_replace(string=education_level,pattern="_3544",replacement=""))%>%
        mutate(education_level=recode(education_level,"HS"="High school or less","SC"="Some college", "BAp"="College graduates"))%>%
        mutate(divorce=divorce*100)
edu_div

I am sure you are aware of the pipe operator as I see you used it throughout your code, but using the pipe operator in this section could help make the wrangling step a bit shorter with fewer objects. 

2.) Data set for plotting names

I read in your comments that you used the annotation function to create the graph but you still wanted to keep this section. I am just curious, why did you want to keep this section? The reason I am asking is that I did not see you use it after creating it. 

Overall amazing job on this exercise!

**Comment by Weifanwu66** [comment]
Hello Jacob, thank you for the comment! The reason that I wanted to leave that data tibble there was because I wanted to remind myself there were different ways to mark lines in the graph! Zane introduced me the annotation function, and I found it really convenient, so I eventually chose to use annotation ( ) instead of `geom_text ( )`
