### ISSUE TITLE
flu analysis not showing

### ISSUE THREAD

**Issue by andreashandel** [Weifanwu66/Weifan-MADA-portfolio#4]
i can't see the flu analysis exercise on your website. looks like you got it in your YAML, so maybe you just forgot to rebuild the website before pushing to Github? 

Since you said you had problems with the YAML, I tried to build the website. Unfortunately I got an error message during building. It seems to try to load a file that doesn't exist. But I didn't seem to have problems with the quarto YAML file. See if you can fix things, run the full website build and push to Github and see if the flu analysis entries show.

I recommend not having 'help()' calls in your quarto files, otherwise when you build your website it keeps opening help browser tabs.

And the link from your website to your github repo also needs to be added to the quarto.yml file.

**Comment by Weifanwu66** [comment]
Hello Dr. Handel, I deleted the extra `Rproj.file` in fluanalysis. I also deleted the help () command in previous coding exercise. The link from my website to my github repo was added to `quarto.yml` file.

**Comment by Weifanwu66** [comment]
> i can't see the flu analysis exercise on your website. looks like you got it in your YAML, so maybe you just forgot to rebuild the website before pushing to Github?
> 
> Since you said you had problems with the YAML, I tried to build the website. Unfortunately I got an error message during building. It seems to try to load a file that doesn't exist. But I didn't seem to have problems with the quarto YAML file. See if you can fix things, run the full website build and push to Github and see if the flu analysis entries show.
> 
> I recommend not having 'help()' calls in your quarto files, otherwise when you build your website it keeps opening help browser tabs.
> 
> And the link from your website to your github repo also needs to be added to the quarto.yml file.

Hello Dr. Handel, I deleted the extra Rproj.file in fluanalysis. I also deleted the help () command in previous coding exercise. The link from my website to my github repo was added to quarto.yml file.
